language: go
sudo: false
go:
  - "1.10.x"
  - tip
before_install:
  - go get github.com/mattn/goveralls
  - bash prepare.sh
  - pwd
  - ls -l
  - ls -l libs/lib/
script:
  - pwd
  - ls -a
  - $GOPATH/bin/goveralls -service=travis-ci
  - bash <(curl -s https://codecov.io/bash)
